version: "3.9"
services:
  server:
    build: ./server
    container_name: flask_server
    ports:
      - "5001:5000"
  client:
    build: ./client
    container_name: python_client
    depends_on:
      - server
